### ISSUE TITLE
Is there a way to accept a more than one word command?

### ISSUE THREAD

**Issue by ZizouHuweidi** [matejc/sway-scratchpad#2]
I have tried to launch a terminal app inside kitty as a scratchpad and I have exhausted every single possibility of passing more than two words for the command but it does not seem to be possible. Is this by design? and if so, how do we get around it if possible?

**Comment by matejc** [comment]
I made a fix https://github.com/matejc/sway-scratchpad/releases/tag/v0.1.4, you should be now able to just run `sway-scratchpad --command "kitty -d /home/user/projects" --mark terminal`

**Comment by ZizouHuweidi** [comment]
> I made a fix https://github.com/matejc/sway-scratchpad/releases/tag/v0.1.4, you should be now able to just run `sway-scratchpad --command "kitty -d /home/user/projects" --mark terminal`

Great to hear. Will be testing it rn. It was the only thing stopping me from using what is otherwise a great solution
